# Generated by Django 5.2.7 on 2025-10-08 11:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('group', 'Group'), ('subgroup', 'Subgroup'), ('organization', 'Organization'), ('location', 'Location'), ('plant', 'Plant'), ('unit', 'Unit'), ('machine', 'Machine'), ('other', 'Other')], max_length=50)),
                ('hierarchy_level', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hierarchy.asset')),
            ],
            options={
                'ordering': ['hierarchy_level', 'asset_name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_plant', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('rooms', models.CharField(blank=True, max_length=255, null=True)),
                ('line', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hierarchy.asset')),
            ],
        ),
    ]
