# Generated by Django 5.2.7 on 2025-10-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['asset_name']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='hierarchy_level',
        ),
        migrations.AddField(
            model_name='asset',
            name='building',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='detail_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer_plant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='rooms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('group', 'Group'), ('subgroup', 'Subgroup'), ('organization', 'Organization'), ('location', 'Location'), ('plant', 'Plant'), ('unit', 'Unit'), ('machine', 'Machine'), ('building', 'Building'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AssetDetail',
        ),
    ]
