# Generated by Django 5.2.7 on 2025-10-10 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_alter_asset_options_remove_asset_hierarchy_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='building',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='detail_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='line',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='manufacturer_plant',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='rooms',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('group', 'Group'), ('subgroup', 'Subgroup'), ('organization', 'Organization'), ('location', 'Location'), ('plant', 'Plant'), ('unit', 'Unit'), ('machine', 'Machine'), ('building', 'building'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='AssetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_plant', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('rooms', models.CharField(blank=True, max_length=255, null=True)),
                ('line', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hierarchy.asset')),
            ],
        ),
    ]
