# Generated by Django 5.2.7 on 2025-10-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('hierarchy', '0003_remove_asset_building_remove_asset_detail_name_and_more'),

]


    operations = [
        migrations.AddField(
            model_name='asset',
            name='hierarchy_level',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('group', 'Group'), ('subgroup', 'Subgroup'), ('organization', 'Organization'), ('location', 'Location'), ('plant', 'Plant'), ('unit', 'Unit'), ('machine', 'Machine'), ('building', 'Building'), ('other', 'Other')], max_length=50),
        ),
    ]
