# Generated by Django 5.2.7 on 2025-10-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_asset_hierarchy_level_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hierarchy_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AssetDetail',
        ),
    ]
