# Generated by Django 5.2.7 on 2025-10-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0006_assetdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('group', 'Group'), ('subgroup', 'Subgroup'), ('plant', 'Plant'), ('location', 'Location'), ('Building', 'Building'), ('Floor', 'Floor'), ('Rooms', 'Rooms'), ('Line', 'Line'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='start_date',
            field=models.DateField(default='2025-10-15'),
        ),
        migrations.DeleteModel(
            name='AssetDetail',
        ),
    ]
